#
# Circle CI configuration. Runs each time we push a new commit to Github
# and takes care of validating the examples.
#
version: 2.1
jobs:
  build:
    docker:
      - image: node:14.16.1-buster-slim
    working_directory: ~/tree-sitter-guidelines
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install -y python3 clang
      - run:
          name: Install npm dependencies
          command: |
            cd examples
            npm install --ignore-scripts
      - run:
          name: Build grammars
          command: |
            cd examples
            ./build-all
      - run:
          name: Test grammars
          command: |
            cd examples
            ./test-all

workflows:
  version: 2

  build-on-push:
    jobs:
      - build
