#! /usr/bin/env bash
#
# Build all the grammars. Some are expected to fail.
#
set -eu

clear_status() {
  rm -f BUILD-OK BUILD-FAIL CI-FAIL
}

# This is super ugly but should be ok, right?
#
# The EXPECT-BUILD-OK and EXPECT-BUILD-FAIL are persistent and set the
# expectations. EXPECT-BUILD-OK is optional. They are consulted by the
# 'test-all' script to determine whether the tests should be
# attempted.
#
check_status() {
  if [[ -e BUILD-FAIL && ! -e EXPECT-BUILD-FAIL ]]; then
    touch CI-FAIL
  elif [[ -e BUILD-OK && -e EXPECT-BUILD-FAIL ]]; then
    touch CI-FAIL
  fi
}

for gramdir in grammars/*; do
  grammar=$(basename "$gramdir")
  (
    cd "$gramdir"
    clear_status
    echo "===== Build $grammar ====="
    {
      if npx tree-sitter generate 2>&1; then
        echo "OK"
        touch BUILD-OK
      else
        echo "FAIL"
        touch BUILD-FAIL
      fi
    } | tee build.out
    check_status
  )
done
