#
# For those who prefer to call 'make' and 'make test'.
# See 'package.json' for the actual build commands.
#

.PHONY: test
test:
	# Install tree-sitter.
	npm install
	# Build and test the grammars.
	./test-all
