#! /usr/bin/env bash
#
# Build all the grammars. Some are expected to fail.
#
set -eu

clear_status() {
  rm -f BUILD-OK BUILD-FAIL CI-FAIL
}

# This is super ugly but should be ok, right?
#
# The EXPECT-BUILD-OK and EXPECT-BUILD-FAIL are persistent and set the
# expectations. EXPECT-BUILD-OK is optional. They are consulted by the
# 'test-all' script to determine whether the tests should be
# attempted.
#
check_build_status() {
  if [[ -e BUILD-FAIL && ! -e EXPECT-BUILD-FAIL ]]; then
    touch CI-FAIL
  elif [[ -e BUILD-OK && -e EXPECT-BUILD-FAIL ]]; then
    touch CI-FAIL
  fi
}

check_test_status() {
  if [[ -e TEST-FAIL && ! -e EXPECT-TEST-FAIL ]]; then
    touch CI-FAIL
  elif [[ -e TEST-OK && -e EXPECT-TEST-FAIL ]]; then
    touch CI-FAIL
  fi
}

status=0

summary_file=$(pwd)/summary.txt
rm -f "$summary_file"
summary () {
  echo $* >> "$summary_file"
}

error_count=0
fail () {
  error_count=$(( error_count + 1 ))
}

# If the grammar name has the '-fail' suffix, it is expected to fail to build.
is_build_expected_to_fail() {
  if [[ "$grammar" == *-fail ]]; then
    echo yes
  else
    echo no
  fi
}

basedir=$(pwd)

#
# Run build + test for each grammar.
#
for gramdir in grammars/*; do
  grammar=$(basename "$gramdir")
  xfail=$(is_build_expected_to_fail)

  cd "$basedir/$gramdir"
  build_success=yes
  {
    echo "===== Build $grammar"
    if npx tree-sitter generate --no-bindings 2>&1; then
      if [[ "$xfail" = yes ]]; then
        fail
        summary "$grammar build: UNEXPECTED SUCCESS"
      else
        summary "$grammar build: expected success"
      fi
    else
      build_success=no
      if [[ "$xfail" = yes ]]; then
        summary "$grammar build: expected fail"
      else
        fail
        summary "$grammar build: UNEXPECTED FAIL"
        cat <<EOF

*** If this is expected to fail permanently, rename the grammar by
    appending '-fail':

      git mv $gramdir $gramdir-fail

EOF
      fi
    fi

    if [[ "$build_success" = no || -e EXPECT-BUILD-FAIL ]]; then
      echo "===== [Skip testing $grammar]"
      summary "$grammar test: skipped"
    else
      echo "===== Test $grammar"
      if npx tree-sitter test 2>&1; then
        summary "$grammar test: success"
      else
        fail
        summary "$grammar test: FAIL"
      fi
    fi
  } | tee output.log
done

#
# Summarize results
#
echo "===== Results"
cat "$summary_file"

if [[ "$error_count" -gt 0 ]]; then
  {
    echo
    echo "$error_count unexpected result(s)."
  }
  exit 1
fi
